In [1]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
movies_data = pd.read_csv('movies.csv')

In [3]:
movies_data.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [4]:
movies_data.shape

(4803, 24)

In [5]:
selected_features = ['genres','keywords','tagline','cast','director']
print(selected_features)

['genres', 'keywords', 'tagline', 'cast', 'director']


In [6]:
combined_features = movies_data['genres']+' '+movies_data['keywords']+' '+movies_data['tagline']+' '+movies_data['cast']+' '+movies_data['director']

In [7]:
print(combined_features)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...                        
4798    Action Crime Thriller united states\u2013mexic...
4799                                                  NaN
4800                                                  NaN
4801                                                  NaN
4802                                                  NaN
Length: 4803, dtype: object


In [8]:
combined_features = combined_features.dropna()

In [9]:
print(combined_features)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...                        
4792    Crime Horror Mystery Thriller japan prostitute...
4793    Drama confession hazing gang member latino lgb...
4795    Drama gang audition police fake homeless actre...
4796    Science Fiction Drama Thriller distrust garage...
4798    Action Crime Thriller united states\u2013mexic...
Length: 3757, dtype: object


In [10]:
# converting the text data to feature vectors

vectorizer = TfidfVectorizer()

In [11]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [12]:
print(feature_vectors)

  (0, 2059)	0.1701479649518548
  (0, 6661)	0.11429421237668091
  (0, 11113)	0.19659464365709167
  (0, 8725)	0.16231873789167722
  (0, 7469)	0.23688181493087848
  (0, 12479)	0.1528997976336656
  (0, 14239)	0.19539014255433562
  (0, 12000)	0.20190521307222728
  (0, 11358)	0.2208017329558662
  (0, 14773)	0.20823298735110954
  (0, 14551)	0.2329808254780701
  (0, 11385)	0.14977293661066507
  (0, 9805)	0.26936700729904856
  (0, 9534)	0.08734535805520414
  (0, 14542)	0.12593255607069875
  (0, 13042)	0.0662280667693844
  (0, 4238)	0.23688181493087848
  (0, 12186)	0.2139246902011623
  (0, 2744)	0.25244839623226556
  (0, 14165)	0.1263712397025473
  (0, 12278)	0.33706405674362216
  (0, 5016)	0.16231873789167722
  (0, 2603)	0.2234527578396162
  (0, 3151)	0.2183472672840518
  (0, 4672)	0.10162340157558672
  :	:
  (3756, 6649)	0.1630164373294472
  (3756, 8312)	0.16780336056424186
  (3756, 7615)	0.18714779291826822
  (3756, 2219)	0.14997884476607481
  (3756, 3621)	0.14997884476607481
  (3756, 7262)	0

In [13]:
# getting the similarity scores using cosine similarity

similarity = cosine_similarity(feature_vectors)

In [14]:
print(similarity)

[[1.         0.06798628 0.03717966 ... 0.00395593 0.01660447 0.0321408 ]
 [0.06798628 1.         0.03129961 ... 0.01041746 0.         0.00377777]
 [0.03717966 0.03129961 1.         ... 0.         0.         0.01083266]
 ...
 [0.00395593 0.01041746 0.         ... 1.         0.00252605 0.01171968]
 [0.01660447 0.         0.         ... 0.00252605 1.         0.00319347]
 [0.0321408  0.00377777 0.01083266 ... 0.01171968 0.00319347 1.        ]]


In [15]:
print(similarity.shape)

(3757, 3757)


In [16]:
movie_name = input(' Enter your favourite movie name : ')

 Enter your favourite movie name : Avatar


In [17]:
# creating a list with all the movie names given in the dataset

list_of_all_titles = movies_data['title'].tolist()
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [18]:
# finding the close match for the movie name given by the user

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
print(find_close_match)

['Avatar']


In [19]:
close_match = find_close_match[0]
print(close_match)

Avatar


In [20]:
# finding the index of the movie with title

index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]
print(index_of_the_movie)

0


In [21]:
# getting a list of similar movies

similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, 1.0000000000000002), (1, 0.06798628042892609), (2, 0.03717965631597433), (3, 0.011596652808772728), (4, 0.10389364833393194), (5, 0.07645059511022394), (6, 0.007756490454018524), (7, 0.034931748583250696), (8, 0.028116140512279533), (9, 0.025267912020723482), (10, 0.012150261346352737), (11, 0.026216112977867616), (12, 0.028664845942982773), (13, 0.06632138832017812), (14, 0.018681774636719845), (15, 0.0331658997514355), (16, 0.02503154936738318), (17, 0.05526684626992862), (18, 0.03670431515627122), (19, 0.03766636297506482), (20, 0.011557550354922324), (21, 0.02875478849368682), (22, 0.044197918932304014), (23, 0.043210851159198656), (24, 0.04235386873113316), (25, 0.0691454608097311), (26, 0.035297811972169066), (27, 0.038563610582772245), (28, 0.037815028241073724), (29, 0.07762907141629034), (30, 0.058452112687774935), (31, 0.02914568875838483), (32, 0.03473329824662725), (33, 0.0), (34, 0.0364360378982715), (35, 0.048088368165498996), (36, 0.08572064063058558), (37, 0.026158

In [22]:
len(similarity_score)

3757

In [23]:
# sorting the movies based on their similarity score

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True) 
print(sorted_similar_movies)

[(0, 1.0000000000000002), (88, 0.2456237418048033), (2175, 0.24509751522773185), (2746, 0.24434629101541427), (46, 0.2030525590466735), (1002, 0.19214217878044373), (804, 0.17489872863107944), (230, 0.1725357124567125), (1429, 0.16541249647993664), (2402, 0.16302164126695387), (781, 0.1628691487762046), (622, 0.15411730595802764), (2010, 0.15082034581087325), (2035, 0.14862436277383456), (742, 0.14823536845459245), (198, 0.14117048385867936), (1632, 0.13659985826730342), (1380, 0.132653364259132), (42, 0.1306785534977514), (269, 0.13043255660358993), (151, 0.12888425239948367), (1541, 0.12739989088486903), (1207, 0.12376782626294126), (2776, 0.12257471165261441), (2934, 0.12185862906361543), (638, 0.11849702523033924), (3529, 0.11839803737153462), (2712, 0.11725658863974783), (747, 0.11598417497938457), (1888, 0.11571015626902514), (1185, 0.11550408524533758), (820, 0.11481865391943756), (447, 0.1146877091943874), (521, 0.11290345214116922), (102, 0.11179987990341045), (1273, 0.1116578

In [24]:
# print the name of similar movies based on the index

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

Movies suggested for you : 

1 . Avatar
2 . Big Hero 6
3 . Ladyhawke
4 . Baby Geniuses
5 . X-Men: Days of Future Past
6 . The One
7 . After the Sunset
8 . Star Wars: Episode II - Attack of the Clones
9 . Broken City
10 . The Others
11 . Inkheart
12 . Body of Lies
13 . Forsaken
14 . Our Kind of Traitor
15 . The Boxtrolls
16 . R.I.P.D.
17 . The Next Three Days
18 . The Man in the Iron Mask
19 . Toy Story 3
20 . The Princess and the Frog
21 . Beowulf
22 . Toy Story
23 . Made of Honor
24 . The Perks of Being a Wallflower
25 . Invaders from Mars
26 . You've Got Mail
27 . Shine
28 . Reign of Assassins
29 . Gangster Squad


In [25]:
movie_name = input(' Enter your favourite movie name : ')

list_of_all_titles = movies_data['title'].tolist()

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)

close_match = find_close_match[0]

index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]

similarity_score = list(enumerate(similarity[index_of_the_movie]))

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True) 

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

 Enter your favourite movie name : Avengers
Movies suggested for you : 

1 . The Avengers
2 . The Covenant
3 . I Dreamed of Africa
4 . Frozen
5 . The Time Machine
6 . Spider-Man
7 . Harry Potter and the Prisoner of Azkaban
8 . Felicia's Journey
9 . Detention
10 . Yentl
11 . Braveheart
12 . RockNRolla
13 . Star Trek: First Contact
14 . Three Kings
15 . A Dangerous Method
16 . Agent Cody Banks 2: Destination London
17 . Scary Movie 3
18 . Fantastic Mr. Fox
19 . Guess Who
20 . Into the Storm
21 . Living Out Loud
22 . The Proposal
23 . 10 Things I Hate About You
24 . Waterworld
25 . Star Trek Into Darkness
26 . The Royal Tenenbaums
27 . Madea Goes to Jail
28 . Revolutionary Road
29 . Fifty Dead Men Walking
