In [1]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
movies_data = pd.read_csv('movies.csv')

In [3]:
movies_data.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [4]:
movies_data.shape

(4803, 24)

In [5]:
selected_features = ['genres','keywords','tagline','cast','director']
print(selected_features)

['genres', 'keywords', 'tagline', 'cast', 'director']


In [6]:
combined_features = movies_data['genres']+' '+movies_data['keywords']+' '+movies_data['tagline']+' '+movies_data['cast']+' '+movies_data['director']

In [7]:
print(combined_features)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...                        
4798    Action Crime Thriller united states\u2013mexic...
4799                                                  NaN
4800                                                  NaN
4801                                                  NaN
4802                                                  NaN
Length: 4803, dtype: object


In [8]:
combined_features = combined_features.dropna()

In [9]:
print(combined_features)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...                        
4792    Crime Horror Mystery Thriller japan prostitute...
4793    Drama confession hazing gang member latino lgb...
4795    Drama gang audition police fake homeless actre...
4796    Science Fiction Drama Thriller distrust garage...
4798    Action Crime Thriller united states\u2013mexic...
Length: 3757, dtype: object


In [10]:
# converting the text data to feature vectors

vectorizer = TfidfVectorizer()

In [11]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [12]:
print(feature_vectors)

  (0, 2059)	0.1701479649518548
  (0, 6661)	0.11429421237668091
  (0, 11113)	0.19659464365709167
  (0, 8725)	0.16231873789167722
  (0, 7469)	0.23688181493087848
  (0, 12479)	0.1528997976336656
  (0, 14239)	0.19539014255433562
  (0, 12000)	0.20190521307222728
  (0, 11358)	0.2208017329558662
  (0, 14773)	0.20823298735110954
  (0, 14551)	0.2329808254780701
  (0, 11385)	0.14977293661066507
  (0, 9805)	0.26936700729904856
  (0, 9534)	0.08734535805520414
  (0, 14542)	0.12593255607069875
  (0, 13042)	0.0662280667693844
  (0, 4238)	0.23688181493087848
  (0, 12186)	0.2139246902011623
  (0, 2744)	0.25244839623226556
  (0, 14165)	0.1263712397025473
  (0, 12278)	0.33706405674362216
  (0, 5016)	0.16231873789167722
  (0, 2603)	0.2234527578396162
  (0, 3151)	0.2183472672840518
  (0, 4672)	0.10162340157558672
  :	:
  (3756, 6649)	0.1630164373294472
  (3756, 8312)	0.16780336056424186
  (3756, 7615)	0.18714779291826822
  (3756, 2219)	0.14997884476607481
  (3756, 3621)	0.14997884476607481
  (3756, 7262)	0

In [13]:
# getting the similarity scores using cosine similarity

similarity = cosine_similarity(feature_vectors)

In [14]:
print(similarity)

[[1.         0.06798628 0.03717966 ... 0.00395593 0.01660447 0.0321408 ]
 [0.06798628 1.         0.03129961 ... 0.01041746 0.         0.00377777]
 [0.03717966 0.03129961 1.         ... 0.         0.         0.01083266]
 ...
 [0.00395593 0.01041746 0.         ... 1.         0.00252605 0.01171968]
 [0.01660447 0.         0.         ... 0.00252605 1.         0.00319347]
 [0.0321408  0.00377777 0.01083266 ... 0.01171968 0.00319347 1.        ]]


In [15]:
print(similarity.shape)

(3757, 3757)


In [16]:
movie_name = input(' Enter your favourite movie name : ')

 Enter your favourite movie name : batman


In [17]:
# creating a list with all the movie names given in the dataset

list_of_all_titles = movies_data['title'].tolist()
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [18]:
# finding the close match for the movie name given by the user

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
print(find_close_match)

['Batman', 'Batman', 'Catwoman']


In [19]:
close_match = find_close_match[0]
print(close_match)

Batman


In [20]:
# finding the index of the movie with title

index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]
print(index_of_the_movie)

1359


In [21]:
# getting a list of similar movies

similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, 0.011447691888789609), (1, 0.010048708351492339), (2, 0.020443668925884544), (3, 0.02597464241552483), (4, 0.0), (5, 0.011987338126267125), (6, 0.0), (7, 0.038286253018464), (8, 0.011854036473708963), (9, 0.011344180291639711), (10, 0.035316736584185444), (11, 0.011769880784886893), (12, 0.0), (13, 0.011434436808615308), (14, 0.029142252965354748), (15, 0.017975973232033406), (16, 0.011238063864152405), (17, 0.0), (18, 0.025300811252154092), (19, 0.011494235333659269), (20, 0.015741362262745934), (21, 0.02633300438299016), (22, 0.009974182388056802), (23, 0.019577153725634563), (24, 0.011130272083558386), (25, 0.0), (26, 0.01590470936340958), (27, 0.0), (28, 0.020793035611018564), (29, 0.011654431950822249), (30, 0.0), (31, 0.02127244576643588), (32, 0.0), (33, 0.0), (34, 0.0), (35, 0.01778510732154818), (36, 0.012060420970320276), (37, 0.01174381597458604), (38, 0.0369785858749582), (39, 0.0), (40, 0.03487825797586676), (41, 0.0), (42, 0.0), (43, 0.0), (44, 0.012428910051969295),

In [22]:
len(similarity_score)

3757

In [24]:
# sorting the movies based on their similarity score

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True) 
print(sorted_similar_movies)

[(68, 1.0000000000000002), (782, 0.1836404246467812), (2251, 0.14967232797211558), (13, 0.14155393632677146), (631, 0.14139432338063246), (585, 0.1412102283834803), (289, 0.14007894529555406), (1387, 0.1399616639876235), (3, 0.1386348882558986), (202, 0.1384424216403353), (330, 0.13127468164349035), (113, 0.13069806392033087), (60, 0.12989839880549592), (63, 0.12695144278009954), (40, 0.12596021521787382), (832, 0.1253379782679509), (1276, 0.12124146158667375), (288, 0.11892661363629653), (1133, 0.11765502967023454), (229, 0.11735011380832404), (1077, 0.11728790559276389), (985, 0.11666247201306422), (156, 0.11484005235679379), (2200, 0.11460266977054516), (415, 0.11363315853494868), (919, 0.1093502464485617), (1096, 0.10810507404286852), (3420, 0.10754452506503706), (508, 0.10625265590405748), (106, 0.10606397541152342), (216, 0.10576308063033885), (295, 0.10564029303499682), (9, 0.10503429519333655), (3493, 0.10488593619875815), (1210, 0.10423669097835649), (1220, 0.10028898834367161

In [23]:
# print the name of similar movies based on the index

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

Movies suggested for you : 



NameError: name 'sorted_similar_movies' is not defined

In [26]:
movie_name = input(' Enter your favourite movie name : ')

list_of_all_titles = movies_data['title'].tolist()

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)

close_match = find_close_match[0]

index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]

similarity_score = list(enumerate(similarity[index_of_the_movie]))

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True) 

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

 Enter your favourite movie name : batman
Movies suggested for you : 

1 . Batman
2 . Multiplicity
3 . Over Her Dead Body
4 . The Chronicles of Narnia: The Lion, the Witch and the Wardrobe
5 . Kingpin
6 . The Barbarian Invasions
7 . Six Days Seven Nights
8 . The Man with the Golden Gun
9 . Lilya 4-ever
10 . The Country Bears
11 . 40 Days and 40 Nights
12 . My Bloody Valentine
13 . Harold & Kumar Go to White Castle
14 . The Legend of Bagger Vance
15 . Old School
16 . Speed Racer
17 . The Whole Nine Yards
18 . The Robe
19 . Milk
20 . I Am Number Four
21 . Faithful
22 . The Midnight Meat Train
23 . Pan's Labyrinth
24 . Two Weeks Notice
25 . Richard III
26 . The Huntsman: Winter's War
27 . Mrs Henderson Presents
28 . How She Move
29 . Never Say Never Again
